depend: [MafanaMysqlAPI]
name: MafanaMarket
version: ${project.version}
main: me.TahaCheji.MafanaMarket
api-version: 1.16
authors: [ TahaCheji ]
description: A place where players can open up shops and list things

commands:
  MafanaMarket: